- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  resourceNameRegexp: "machine-driver-secret$|machine-provision$|admission-configuration-psact$|^harvesterconfig|^registryconfig-auth|^harvester-cloud-provider-config"
  namespaces:
  - "fleet-default"
- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  namespaces:
   - "fleet-default"
  fieldSelectors:
      "type": "rke.cattle.io/machine-plan"
- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  namespaces:
   - "fleet-default"
  fieldSelectors:
      "type": "rke.cattle.io/cluster-state"
- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  namespaces:
   - "fleet-default"
  fieldSelectors:
      "type": "rke.cattle.io/machine-state"
