# kubewarden secrets:
- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  labelSelectors:
    matchExpressions:
    - key: "app.kubernetes.io/part-of"
      operator: "In"
      values: ["kubewarden"]
  namespaceRegexp: "^cattle-kubewarden-|^kubewarden"
# policy-reporter, policy-reporter-ui subchart secrets:
- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  labelSelectors:
    matchExpressions:
    - key: "app.kubernetes.io/instance"
      operator: "In"
      values: ["kubewarden-controller"]
    - key: "app.kubernetes.io/name"
      operator: "In"
      values: ["policy-reporter", "policy-reporter-ui"]
