version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: _test.go
      - linters:
          - revive
        path: pkg/util
      - linters:
          - revive
        path: cmd/operator/version/version.go
        text: var-naming
    paths:
      - /zz_generated_
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - /zz_generated_
