linters:
  disable-all: true
  enable:
    - govet
    - revive
    - goimports
    - misspell
    - ineffassign
    - gofmt
run:
  timeout: 5m
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - revive
  exclude-files:
    - "/zz_generated_"