# Make sure to check the documentation at https://goreleaser.com
version: 2 # the goreleaser config version
before:
  hooks:
    - go mod tidy
builds:
    - id: backup-restore-operator
      main: ./cmd/operator/main.go
      goos:
        - linux
      goarch:
        - amd64
        - arm64
      binary: backup-restore-operator
      ldflags:
        - -extldflags
        - -static
        - -s
        - -X github.com/rancher/backup-restore-operator/cmd/operator/version.Version={{.Version}}
        - -X github.com/rancher/backup-restore-operator/cmd/operator/version.GitCommit={{.Commit}}
        - -X github.com/rancher/backup-restore-operator/cmd/operator/version.Date={{.Date}}
      flags:
        - -trimpath
      env:
        - CGO_ENABLED=0

  # macOS build, only when GOOS_DARWIN_DEV is set
    - id: backup-restore-operator-darwin
      main: ./cmd/operator/main.go
      goos:
        - darwin
      goarch:
        - amd64
        - arm64
      binary: backup-restore-operator
      ldflags:
        - -s
        - -X github.com/rancher/backup-restore-operator/cmd/operator/version.Version={{.Version}}
        - -X github.com/rancher/backup-restore-operator/cmd/operator/version.GitCommit={{.Commit}}
        - -X github.com/rancher/backup-restore-operator/cmd/operator/version.Date={{.Date}}
      flags:
        - -trimpath
      env:
        - CGO_ENABLED=0
      skip: '{{ not (index .Env "GOOS_DARWIN_DEV") }}'

archives:
    - id: backup-restore-operator
      builds:
        - backup-restore-operator 
      name_template: '{{ .Binary }}-{{ .Arch }}'
release:
  prerelease: auto
  extra_files:
    - glob : ./build/artifacts/*.tgz
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
