- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  labelSelectors:
    matchExpressions:
      - key: "cluster.x-k8s.io/cluster-name"
        operator: "Exists"
- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  fieldSelectors:
    "type": "addons.cluster.x-k8s.io/resource-set"
- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  namespaceRegexp: "^capi-|^capa-|^capd-|^capg-|^capv-|^capz-|^rke2-bootstrap-system$|^rke2-control-plane-system$|^fleet-addon-system$"
  labelSelectors:
    matchExpressions:
      - key: "owner"
        operator: "NotIn"
        values: ["helm"]
