- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  labelSelectors:
    matchExpressions:
    - key: "elemental.cattle.io/managed"
      operator: "In"
      values: ["true"]
  namespaceRegexp: "^cattle-fleet-|^fleet-"
