- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  namespaceRegexp: "^cattle-fleet-|^fleet-"
  excludeResourceNameRegexp: "^import-token"
  labelSelectors:
    matchExpressions:
      - key: "owner"
        operator: "NotIn"
        values: ["helm"]
      - key: "fleet.cattle.io/managed"
        operator: "In"
        values: ["true"]
