- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  namespaceRegexp: "^cattle-|^p-|^c-|^local$|^user-|^u-"
  labelSelectors:
    matchExpressions:
      - key: "owner"
        operator: "NotIn"
        values: ["helm"]
  excludeResourceNameRegexp: "^bootstrap-secret$|^rancher-csp-adapter|^csp-adapter-cache$"
- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  namespaceRegexp: "^.*$"
  labelSelectors:
    matchExpressions:
      - key: "resources.cattle.io/backup"
        operator: "In"
        values: ["true"]
