#!/usr/bin/env bash

echo "-- chart/test --"

# skipping tests for s390x since helm v2 doesn't support s390x yet
if [ ${ARCH} == s390x ]; then
    exit 0
fi

# Check for helm
if [ -z "$(type -p helm)" ]; then
    echo "helm not found. Helm is required to run tests."
    exit 1
fi

# Check for unittest plugin
HELM_PLUGINS=/root/.local/share/helm/plugins/ helm unittest --help >/dev/null 2>&1
if [[ $? > 0 ]]; then
    echo "helm plugin unittest not found."
    echo "Run to install plugin: helm plugin install https://github.com/quintush/helm-unittest"
    exit 1
fi


HELM_PLUGINS=/root/.local/share/helm/plugins/ helm unittest --helm3 ../build/charts/rancher-backup
