#!/bin/bash
set -e

cd $(dirname $0)/..
source ./scripts/version

if [[ ! -d ./dist/artifacts ]] || [[ ! -f "./dist/artifacts/rancher-backup-${HELM_CHART_VERSION}.tgz" ]]; then
  ./scripts/package-helm
fi

cd tests
echo "Running Hull Tests on Chart Version: $HELM_CHART_VERSION"
go test -race -timeout 30s -run ^TestChart$ github.com/rancher/backup-restore-operator/tests/hull

cd ..
