#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

cd tests
echo "Running Hull Tests"
if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    go test -timeout 30s -run ^TestChart$ github.com/rancher/backup-restore-operator/tests/hull -helm_version=$HELM_VERSION
else
    go test -timeout 30s -run ^TestChart$ github.com/rancher/backup-restore-operator/tests/hull -helm_version=$HELM_VERSION_DEV
fi

cd ..
