#!/bin/bash
set -e

function edit-charts() {
    sed -i \
        -e 's/^version:.*/version: '${1}'/' \
        -e 's/^appVersion:.*/appVersion: '${1}'/' \
        build/charts/rancher-backup/Chart.yaml

    sed -i \
        -e 's/%TAG%/'${2}'/' \
        -e 's/%VERSION%/'${3}'/' \
        build/charts/rancher-backup/values.yaml

    sed -i \
        -e 's/^version:.*/version: '${1}'/' \
        -e 's/^appVersion:.*/appVersion: '${1}'/' \
        build/charts/rancher-backup-crd/Chart.yaml
}

function package-charts() {
    helm package --debug -d ./dist/artifacts ./build/charts/rancher-backup
    helm package --debug -d ./dist/artifacts ./build/charts/rancher-backup-crd
}

if ! hash helm 2>/dev/null; then
    echo "Helm is not installed"
    exit 1
fi

cd $(dirname $0)/..
. ./scripts/version

rm -rf build/charts
mkdir -p build dist/artifacts
cp -rf charts build/

edit-charts ${HELM_VERSION} ${HELM_TAG} ${VERSION}

if ! package-charts; then
    echo "package-chart or package-chart-crd failed: trying with dev variable..."
    edit-charts ${HELM_VERSION_DEV} ${HELM_TAG_DEV}
    package-charts
fi
