#!/bin/bash
set -e


function edit-charts() {
    perl -i -pe '
    s/^version:.*/version: '"${1}"'/;
    s/^appVersion:.*/appVersion: '\"${2}\"'/;
    s/catalog\.cattle\.io\/upstream-version:.*/catalog.cattle.io\/upstream-version: '"${1}"'/
' build/charts/rancher-backup/Chart.yaml

    perl -i -pe 's/%TAG%/'"${2}"'/' build/charts/rancher-backup/values.yaml

    perl -i -pe '
    s/^version:.*/version: '"${1}"'/;
    s/^appVersion:.*/appVersion: '\"${2}\"'/
' build/charts/rancher-backup-crd/Chart.yaml
}

function package-charts() {
    helm package --debug -d ./dist/artifacts ./build/charts/rancher-backup
    helm package --debug -d ./dist/artifacts ./build/charts/rancher-backup-crd
}

if ! hash helm 2>/dev/null; then
    echo "Helm is not installed"
    exit 1
fi

cd $(dirname $0)/..
source ./scripts/version


rm -rf build/charts
mkdir -p build dist/artifacts
cp -rf charts build/

edit-charts ${HELM_CHART_VERSION} ${HELM_IMAGE_TAG}

if ! package-charts; then
    echo "Packaging the BRO charts failed!"
fi
