- apiVersion: "apiextensions.k8s.io/v1"
  kindsRegexp: "."
  resourceNameRegexp: "turtles-capi.cattle.io$"
- apiVersion: "turtles-capi.cattle.io/v1alpha1"
  kindsRegexp: "."
- apiVersion: "infrastructure.cluster.x-k8s.io/v1beta2"
  kindsRegexp: "."
- apiVersion: "vmware.infrastructure.cluster.x-k8s.io/v1beta2"
  kindsRegexp: "."
- apiVersion: "controlplane.cluster.x-k8s.io/v1beta2"
  kindsRegexp: "."
- apiVersion: "bootstrap.cluster.x-k8s.io/v1beta2"
  kindsRegexp: "."
- apiVersion: "addons.cluster.x-k8s.io/v1beta2"
  kindsRegexp: "."
- apiVersion: "addons.cluster.x-k8s.io/v1alpha1"
  kindsRegexp: "."
- apiVersion: "ipam.cluster.x-k8s.io/v1beta2"
  kindsRegexp: "."
- apiVersion: "runtime.cluster.x-k8s.io/v1beta2"
  kindsRegexp: "."
- apiVersion: "v1"
  kindsRegexp: "^namespaces$"
  resourceNameRegexp: "^capi-system$|^capi-operator-system$|^capi-providers$|^capi-kubeadm-bootstrap-system$|^capi-kubeadm-control-plane-system$|^capa-system$|^capd-system$|^capg-system$|^capv-system$|^capz-system$|^rke2-bootstrap-system$|^rke2-control-plane-system$|^fleet-addon-system$|^rancher-turtles-system$"
- apiVersion: "v1"
  kindsRegexp: "^configmaps$"
  namespaceRegexp: "^capi-|^capa-|^capd-|^capg-|^capv-|^capz-|^rke2-bootstrap-system$|^rke2-control-plane-system$|^fleet-addon-system$|^rancher-turtles-system$|^cattle-turtles-|^cattle-capi-"
  excludeResourceNameRegexp: "^kube-root-ca.crt$"
- apiVersion: "v1"
  kindsRegexp: "^configmaps$"
  labelSelectors:
    matchExpressions:
      - key: "managed-by.turtles.cattle.io"
        operator: "In"
        values: ["true"]
