- apiVersion: "v1"
  kindsRegexp: "^namespaces$"
  resourceNameRegexp: "^cattle-|^p-|^c-|^user-|^u-|^local-"
  resourceNames:
    - "local"
- apiVersion: "v1"
  kindsRegexp: "^serviceaccounts$"
  namespaceRegexp: "^cattle-|^p-|^c-|^local$|^user-|^u-"
  excludeResourceNameRegexp: "^default$|^rancher-csp-adapter$"
- apiVersion: "v1"
  kindsRegexp: "^configmaps$"
  namespaces:
    - "cattle-system"
- apiVersion: "v1"
  kindsRegexp: "^configmaps$"
  namespaceRegexp: "^cattle-"
  labelSelectors:
    matchExpressions:
      - key: "cattle.io/kind"
        operator: "In"
        values: [ "kubeconfig" ]
- apiVersion: "rbac.authorization.k8s.io/v1"
  kindsRegexp: "^roles$|^rolebindings$"
  namespaceRegexp: "^cattle-|^p-|^c-|^local$|^user-|^u-"
  excludeResourceNameRegexp: "^rancher-csp-adapter"
- apiVersion: "rbac.authorization.k8s.io/v1"
  kindsRegexp: "^clusterrolebindings$"
  resourceNameRegexp: "^cattle-|^clusterrolebinding-|^globaladmin-user-|^grb-u-|^crb-"
- apiVersion: "rbac.authorization.k8s.io/v1"
  kindsRegexp: "^clusterroles$"
  resourceNameRegexp: "^cattle-|^p-|^c-|^local-|^user-|^u-|^project-|^create-ns$"
  excludeResourceNameRegexp: "^rancher-csp-adapter-"
- apiVersion: "scheduling.k8s.io/v1"
  kindsRegexp: "^priorityclasses$"
  resourceNameRegexp: "^rancher-critical$"
- apiVersion: "apiextensions.k8s.io/v1"
  kindsRegexp: "."
  resourceNameRegexp: "management.cattle.io$|project.cattle.io$|catalog.cattle.io$|resources.cattle.io$"
- apiVersion: "management.cattle.io/v3"
  kindsRegexp: "."
  excludeKinds:
    - "tokens"
    - "rancherusernotifications"
- apiVersion: "management.cattle.io/v3"
  kindsRegexp: "^tokens$"
  labelSelectors:
    matchExpressions:
      - key: "authn.management.cattle.io/kind"
        operator: "NotIn"
        values: [ "provisioning" ]
- apiVersion: "project.cattle.io/v3"
  kindsRegexp: "."
- apiVersion: "catalog.cattle.io/v1"
  kindsRegexp: "^clusterrepos$"
- apiVersion: "resources.cattle.io/v1"
  kindsRegexp: "^ResourceSet$"
- apiVersion: catalog.cattle.io/v1
  kindsRegexp: ^UIPlugin$
  namespaces:
  - cattle-ui-plugin-system
