apiVersion: resources.cattle.io/v1
kind: ResourceSet
metadata:
  name: rancher-resource-set-full
controllerReferences:
  - apiVersion: "apps/v1"
    resource: "deployments"
    name: "rancher"
    namespace: "cattle-system"
resourceSelectors:
{{- range $path, $_ := .Files.Glob "files/default-resourceset-contents/*.yaml" -}}
  {{- $.Files.Get $path | nindent 2 -}}
{{- end -}}
{{- range $path, $_ := .Files.Glob "files/sensitive-resourceset-contents/*.yaml" -}}
  {{- $.Files.Get $path | nindent 2 -}}
{{- end -}}
