apiVersion: resources.cattle.io/v1
kind: ResourceSet
metadata:
  name: rancher-resource-set-basic
controllerReferences:
  - apiVersion: "apps/v1"
    resource: "deployments"
    name: "rancher"
    namespace: "cattle-system"
resourceSelectors:
{{- /* Includes default resources into the ResourceSet */ -}}
{{- range $path, $_ := .Files.Glob "files/default/basic-resourceset-contents/*.yaml" -}}
  {{- $.Files.Get $path | nindent 2 -}}
{{- end -}}

{{- /* Include all optional resources into the ResourceSet based on what's enabled */ -}}
{{- range $key, $val := .Values.optionalResources }}
  {{- if $val.enabled }}
    {{- $globPattern := printf "files/optional/basic-resourceset-contents/%s.yaml" $key }}
    {{- range $path, $_ := $.Files.Glob $globPattern }}
      {{- $.Files.Get $path | nindent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
