- apiVersion: "apiextensions.k8s.io/v1"
  kindsRegexp: "."
  resourceNameRegexp: "provisioning.cattle.io$|rke-machine-config.cattle.io$|rke-machine.cattle.io$|rke.cattle.io$|cluster.x-k8s.io$"
- apiVersion: "provisioning.cattle.io/v1"
  kindsRegexp: "."
- apiVersion: "rke-machine-config.cattle.io/v1"
  kindsRegexp: "."
- apiVersion: "rke-machine.cattle.io/v1"
  kindsRegexp: "."
- apiVersion: "rke.cattle.io/v1"
  kindsRegexp: "."
- apiVersion: "cluster.x-k8s.io/v1beta1"
  kindsRegexp: "."
- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  namespaces:
  - "fleet-default"
  labelSelectors:
    matchExpressions:
      - key: "provisioning.cattle.io/managed"
        operator: "In"
        values: ["true"]
- apiVersion: "v1"
  kindsRegexp: "^configmaps$"
  resourceNames:
    - "provisioning-log"
  namespaceRegexp: "^c-m-"
