name: Backup Restore CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - release/v[0-9]+.(0|x)
      - release/v[0-9]+.[0-9]+.[0-9]+
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'

jobs:
  ci:
    uses: rancher/backup-restore-operator/.github/workflows/ci.yaml@automation-core
    with:
      k3s_versions: '["v1.30.14-k3s2", "v1.32.12-k3s1"]'
    permissions:
      contents: read
    secrets: inherit
