name: Backup Restore CI

permissions:
  contents: read

on:
  workflow_call:
  push:
    branches:
      - main
      - release/v[0-9]+.(0|x)
      - release/v[0-9]+.[0-9]+.[0-9]+
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '*.md'
    - '.gitignore'
    - 'CODEOWNERS'
    - 'LICENSE'
jobs:
  ci:
    uses: diogoasouza/backup-restore-operator/.github/workflows/ci.yaml@automation-core
    permissions:
      contents: read
    secrets: inherit
