name : Branch head Prerelease Images

on:
  workflow_call:

env:
  REGISTRY: docker.io
  REPO : rancher

permissions:
  contents: write

jobs:
  prebuild-env:
    name: Prebuild needed Env vars
    runs-on : runs-on,image=ubuntu22-full-x64,runner=4cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: rancher/backup-restore-operator/actions/compute-branch-tags@automation-core
        id: set-vars
    outputs:
      branch_tag: ${{ steps.set-vars.outputs.branch_tag }}
      branch_static_tag: ${{ steps.set-vars.outputs.branch_static_tag }}
      prev_tag: ${{ steps.set-vars.outputs.prev_static_tag }}
  push:
    needs : [
      prebuild-env,
    ]
    permissions:
      contents : read
      id-token: write
    name : Build and push BRO images
    runs-on : runs-on,image=ubuntu22-full-x64,runner=4cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - name : "Read vault secrets"
        uses : rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        if: ${{ github.repository_owner == 'rancher' }}
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
      - name : Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout bin-deps config to local branch
        shell: bash
        run: git restore --source automation-core .bin-deps.yaml

      - uses: rancherlabs/dep-fetch/actions/sync-deps@c20b0b0e73e0819fd96fab41e1ee8987714dd04b # v0.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Log in to the Container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME || vars.REPO }}
          password: ${{ env.DOCKER_PASSWORD || secrets.DOCKER_PW }}
      - name: Build and push BRO image
        env:
          FULL_IMAGE_URL: "${{ env.REGISTRY }}/${{ vars.REPO || env.REPO || github.repository_owner }}/backup-restore-operator"
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ./package/Dockerfile
          build-args: |
            TAG=${{ needs.prebuild-env.outputs.branch_static_tag }}
          push: true
          tags: ${{ env.FULL_IMAGE_URL }}:${{ needs.prebuild-env.outputs.branch_static_tag }}
          platforms: linux/amd64,linux/arm64
      - name: Update rolling tag to new static tag
        env:
          FULL_IMAGE_URL: ${{ env.REGISTRY }}/${{ vars.REPO || env.REPO || github.repository_owner }}/backup-restore-operator
        run: |
          oras copy ${{ env.FULL_IMAGE_URL }}:${{ needs.prebuild-env.outputs.branch_static_tag }} ${{ env.FULL_IMAGE_URL }}:${{ needs.prebuild-env.outputs.branch_tag }}
