name: Publish Images & artifacts (via goreleaser)

on:
  push:
    tags:
      - "*"

jobs:
  release:
    uses: rancher/backup-restore-operator/.github/workflows/release.yaml@automation-core
    with:
      k3s_versions: '["v1.34.5-k3s1", "v1.36.1-k3s1"]'
    permissions:
      contents: write
      id-token: write
      attestations: write
    secrets: inherit
